config/routes.rb
require 'api_version'
Rails.application.routes.draw do
  resources :translations
  resources :translations_ens
  resources :translations_ars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      resources :translations
    end
  end

  # root to: 'pages#index'
  get "pages" => "pages#index"
  get "change_locale" => "pages#change_locale"

end

app/models/translations_en.rb
class TranslationsEn < ApplicationRecord
end

app/controllers/translations_ens_controller.rb
class TranslationsEnsController < ApplicationController
  before_action :set_translations_en, only: [:show, :edit, :update, :destroy]

  # GET /translations_ens
  # GET /translations_ens.json
  def index
    @translations_ens = TranslationsEn.all
  end

  # GET /translations_ens/1
  # GET /translations_ens/1.json
  def show
  end

  # GET /translations_ens/new
  def new
    @translations_en = TranslationsEn.new
  end

  # GET /translations_ens/1/edit
  def edit
  end

  # POST /translations_ens
  # POST /translations_ens.json
  def create
    @translations_en = TranslationsEn.new(translations_en_params)

    respond_to do |format|
      if @translations_en.save
        format.html { redirect_to @translations_en, notice: 'Translations en was successfully created.' }
        format.json { render :show, status: :created, location: @translations_en }
      else
        format.html { render :new }
        format.json { render json: @translations_en.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations_ens/1
  # PATCH/PUT /translations_ens/1.json
  def update
    respond_to do |format|
      if @translations_en.update(translations_en_params)

        @textt = params[:translations_en][:text].to_s
        @data = YAML.load_file "config/locales/en.yml"
        @data["en"]["#{@textt}"] = params[:translations_en][:translation]
        File.open("config/locales/en.yml", 'w') { |f| YAML.dump(@data, f) }

        format.html { redirect_to @translations_en, notice: 'Translations en was successfully updated.' }
        format.json { render :show, status: :ok, location: @translations_en }
      else
        format.html { render :edit }
        format.json { render json: @translations_en.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations_ens/1
  # DELETE /translations_ens/1.json
  def destroy
    @translations_en.destroy
    respond_to do |format|
      format.html { redirect_to translations_ens_url, notice: 'Translations en was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translations_en
      @translations_en = TranslationsEn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translations_en_params
      params.require(:translations_en).permit(:text, :translation)
    end
end

app/helpers/translations_ens_helper.rb
module TranslationsEnsHelper
end

app/views/translations_ens/_form.html.erb
<%= form_with(model: translations_en, local: true) do |form| %>
  <% if translations_en.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translations_en.errors.count, "error") %> prohibited this translations_en from being saved:</h2>

      <ul>
      <% translations_en.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :translation %>
    <%= form.text_field :translation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/translations_ens/edit.html.erb
<h1>Editing English Translations</h1>

<%= form_with(model: @translations_en, local: true) do |form| %>
    <% if @translations_en.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(translations_en.errors.count, "error") %> prohibited this translations_en from being saved:</h2>
  
        <ul>
        <% @translations_en.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :text %>
      <%= form.text_field :text , readonly: true %>
    </div>
  
    <div class="field">
      <%= form.label :translation %>
      <%= form.text_field :translation %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Show', @translations_en %> |
<%= link_to 'Back', translations_ens_path %>

app/views/translations_ens/index.html.erb
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<p id="notice"><%= notice %></p>

<h1 style= "padding-left: 15px;"> English Translations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Text</th>
      <th> English Translation</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @translations_ens.each do |translations_en| %>
      <tr>
        <td><%= translations_en.text %></td>
        <td><%= translations_en.translation %></td>
        <td><%= link_to 'Show', translations_en %></td>
        <td><%= link_to 'Edit', edit_translations_en_path(translations_en) %></td>
        <!-- <td><%# link_to 'Destroy', translations_en, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h5 style= "padding-left: 15px;"><%= link_to 'New English Translations', new_translations_en_path %></h5>
</body>

app/views/translations_ens/new.html.erb
<h1>New English Translations</h1>

<%= render 'form', translations_en: @translations_en %>

<%= link_to 'Back', translations_ens_path %>

app/views/translations_ens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @translations_en.text %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @translations_en.translation %>
</p>

<%= link_to 'Edit', edit_translations_en_path(@translations_en) %> |
<%= link_to 'Back', translations_ens_path %>