config/routes.rb
require 'api_version'
Rails.application.routes.draw do
  resources :translations
  resources :translations_ens
  resources :translations_ars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiVersion.new('v1', true) do
      resources :translations
    end
  end

  # root to: 'pages#index'
  get "pages" => "pages#index"
  get "change_locale" => "pages#change_locale"

end

app/models/translations_ar.rb
class TranslationsAr < ApplicationRecord
end

app/controllers/translations_ars_controller.rb
class TranslationsArsController < ApplicationController
  before_action :set_translations_ar, only: [:show, :edit, :update, :destroy]

  # GET /translations_ars
  # GET /translations_ars.json
  def index
    @translations_ars = TranslationsAr.all
  end

  # GET /translations_ars/1
  # GET /translations_ars/1.json
  def show
  end

  # GET /translations_ars/new
  def new
    @translations_ar = TranslationsAr.new
  end

  # GET /translations_ars/1/edit
  def edit
  end

  # POST /translations_ars
  # POST /translations_ars.json
  def create
    @translations_ar = TranslationsAr.new(translations_ar_params)

    respond_to do |format|
      if @translations_ar.save
        format.html { redirect_to @translations_ar, notice: 'Translations ar was successfully created.' }
        format.json { render :show, status: :created, location: @translations_ar }
      else
        format.html { render :new }
        format.json { render json: @translations_ar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations_ars/1
  # PATCH/PUT /translations_ars/1.json
  def update
    respond_to do |format|
      if @translations_ar.update(translations_ar_params)
        @textt = params[:translations_ar][:text].to_s
        @data = YAML.load_file "config/locales/ar.yml"
        @data["ar"]["#{@textt}"] = params[:translations_ar][:translation]
        File.open("config/locales/ar.yml", 'w') { |f| YAML.dump(@data, f) }

        format.html { redirect_to @translations_ar, notice: 'Translations ar was successfully updated.' }
        format.json { render :show, status: :ok, location: @translations_ar }
      else
        format.html { render :edit }
        format.json { render json: @translations_ar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations_ars/1
  # DELETE /translations_ars/1.json
  def destroy
    @translations_ar.destroy
    respond_to do |format|
      format.html { redirect_to translations_ars_url, notice: 'Translations ar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translations_ar
      @translations_ar = TranslationsAr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translations_ar_params
      params.require(:translations_ar).permit(:text, :translation)
    end
end

app/helpers/translations_ars_helper.rb
module TranslationsArsHelper
end

app/views/translations_ars/_form.html.erb
<%= form_with(model: translations_ar, local: true) do |form| %>
  <% if translations_ar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translations_ar.errors.count, "error") %> prohibited this translations_ar from being saved:</h2>

      <ul>
      <% translations_ar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :translation %>
    <%= form.text_field :translation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/translations_ars/edit.html.erb
<h1>Editing Arabic Translations</h1>

<%= form_with(model: @translations_ar, local: true) do |form| %>
    <% if @translations_ar.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(translations_ar.errors.count, "error") %> prohibited this translations_ar from being saved:</h2>
  
        <ul>
        <% @translations_ar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :text %>
      <%= form.text_field :text , readonly: true %>
    </div>
  
    <div class="field">
      <%= form.label :translation %>
      <%= form.text_field :translation %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%# render 'form', translations_ar: @translations_ar %>

<%= link_to 'Show', @translations_ar %> |
<%= link_to 'Back', translations_ars_path %>

app/views/translations_ars/index.html.erb
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<p id="notice"><%= notice %></p>
<h1 style= "padding-left: 15px;">Arabic Translations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Text</th>
      <th> Arabic Translation</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @translations_ars.each do |translations_ar| %>
      <tr>
        <td><%= translations_ar.text %></td>
        <td><%= translations_ar.translation %></td>
        <td><%= link_to 'Show', translations_ar %></td>
        <td><%= link_to 'Edit', edit_translations_ar_path(translations_ar) %></td>
        <!-- <td><%# link_to 'Destroy', translations_ar, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h5 style= "padding-left: 15px;"><%= link_to 'New Arabic Translations', new_translations_ar_path %><h5>
</body>

app/views/translations_ars/new.html.erb
<h1>New Arabic Translations</h1>

<%= render 'form', translations_ar: @translations_ar %>

<%= link_to 'Back', translations_ars_path %>

app/views/translations_ars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @translations_ar.text %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @translations_ar.translation %>
</p>

<%= link_to 'Edit', edit_translations_ar_path(@translations_ar) %> |
<%= link_to 'Back', translations_ars_path %>